(() => {
  if (window.__SPG_ACTIVE__) return;
  window.__SPG_ACTIVE__=true;
  const ID='spg-floating-root';
  let minimized=false;
  const style=document.createElement('style');
  style.textContent=`#${ID}{position:fixed;right:22px;bottom:22px;width:380px;z-index:2147483647;font-family:Inter,system-ui,-apple-system,"Segoe UI",sans-serif;color:#f7f7fa}#${ID} *{box-sizing:border-box}#${ID}.min .spg-panel{display:none}.spg-panel{background:linear-gradient(180deg,#11131a,#090b10);border:1px solid #2b2e3b;border-radius:20px;box-shadow:0 25px 80px #000b,0 0 0 1px #ffffff05;overflow:hidden}.spg-head{height:54px;display:flex;align-items:center;justify-content:space-between;padding:0 12px;border-bottom:1px solid #222530;cursor:move}.spg-brand{display:flex;align-items:center;gap:9px}.spg-heart{width:31px;height:31px;display:grid;place-items:center;border-radius:10px;background:#17101e;border:1px solid #3a244d;color:#b56cff}.spg-name{font-size:11px;font-weight:800}.spg-sub{font-size:8px;color:#727886;margin-top:2px}.spg-controls{display:flex;gap:4px}.spg-controls button{width:27px;height:27px;border:1px solid #292d37;background:#12151b;color:#9da3af;border-radius:8px;cursor:pointer}.spg-controls button:hover{color:#fff;background:#1a1e27}.spg-body{padding:12px}.spg-ta{width:100%;height:125px;resize:vertical;border:1px solid #292d38;border-radius:12px;background:#080a0f;color:#f4f5f8;padding:11px;outline:0;font:11px/1.5 inherit}.spg-ta:focus{border-color:#7950c9;box-shadow:0 0 0 3px #7950c91a}.spg-tools{display:flex;justify-content:space-between;margin-top:7px}.spg-tools button{border:1px solid #252934;background:#12151b;color:#a4a9b5;border-radius:8px;padding:7px 9px;font-size:9px;cursor:pointer}.spg-tools button:hover{background:#1a1e27;color:#fff}.spg-improve{width:100%;margin-top:8px;height:36px;border:1px solid #3b2b50;background:#17111f;color:#d8c8ee;border-radius:9px;cursor:pointer;font-weight:750;font-size:9px}.spg-send{width:100%;margin-top:7px;height:39px;border:0;background:linear-gradient(135deg,#8750d8,#5d67ff);color:#fff;border-radius:9px;cursor:pointer;font-weight:800;font-size:9px}.spg-status{text-align:center;height:15px;font-size:8px;color:#9d72e0;margin-top:5px}.spg-fab{width:48px;height:48px;border:1px solid #40285a;border-radius:15px;background:linear-gradient(145deg,#1d1327,#0d0b12);color:#b56cff;font-size:18px;cursor:pointer;box-shadow:0 15px 40px #000a}.spg-fab:hover{transform:translateY(-2px)}#${ID}.min .spg-fab{display:block}.spg-fab{display:none}`;
  document.documentElement.appendChild(style);
  const root=document.createElement('div');root.id=ID;root.innerHTML=`<div class="spg-panel"><div class="spg-head"><div class="spg-brand"><div class="spg-heart">♥</div><div><div class="spg-name">Sessão Prêmio Gustavo</div><div class="spg-sub">IA local • sem API externa</div></div></div><div class="spg-controls"><button data-a="min" title="Minimizar">−</button><button data-a="close" title="Sair">×</button></div></div><div class="spg-body"><textarea class="spg-ta" placeholder="Escreva o que você quer criar no Lovable..."></textarea><div class="spg-tools"><button data-a="voice">🎙 Falar</button><button data-a="copy">⧉ Copiar</button><button data-a="clear">⌫ Limpar</button></div><button class="spg-improve" data-a="improve">✦ Melhorar com Gustavo Local</button><button class="spg-send" data-a="send">Colocar no chat do Lovable ↗</button><div class="spg-status"></div></div></div><button class="spg-fab" data-a="open">♥</button>`;document.body.appendChild(root);
  const $=(s)=>root.querySelector(s),ta=$('.spg-ta'),status=$('.spg-status');
  function improve(){if(!ta.value.trim()){ta.focus();return}ta.value=`OBJETIVO\n${ta.value.trim()}\n\nREQUISITOS\n- Implementação funcional e completa.\n- Preserve a intenção original.\n- Organize funcionalidades, UI/UX, comportamento e critérios de conclusão.\n- Interface moderna, responsiva e acessível.\n- Trate estados de erro, carregamento, vazio e sucesso.\n\nENTREGA\n- Código pronto para produção e componentes reutilizáveis.`;status.textContent='✦ Melhorado localmente'}
  async function copy(){try{await navigator.clipboard.writeText(ta.value);status.textContent='✓ Copiado'}catch{status.textContent='Não foi possível copiar'}}
  async function send(){if(!ta.value.trim())return;try{await navigator.clipboard.writeText(ta.value)}catch{}chrome.storage.local.set({pendingLovablePrompt:ta.value,lastPrompt:ta.value});fillNativeChat(ta.value);status.textContent='✓ Prompt preparado no Lovable'}
  function fillNativeChat(text){const candidates=[...document.querySelectorAll('textarea,input, [contenteditable="true"]')].filter(e=>!root.contains(e));const target=candidates.find(e=>{const p=(e.getAttribute('placeholder')||'').toLowerCase();return p.includes('message')||p.includes('mensag')||p.includes('prompt')||p.includes('ask')||p.includes('chat')})||candidates[candidates.length-1];if(!target)return;target.focus();if(target.isContentEditable)target.textContent=text;else{const setter=Object.getOwnPropertyDescriptor(Object.getPrototypeOf(target),'value')?.set;if(setter)setter.call(target,text);else target.value=text}target.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:text}));}
  function blockNativeChat(){const els=[...document.querySelectorAll('textarea,input,[contenteditable="true"]')].filter(e=>!root.contains(e));els.forEach(e=>{const p=(e.getAttribute('placeholder')||'').toLowerCase();if(p.includes('message')||p.includes('mensag')||p.includes('ask')||p.includes('prompt')){e.dataset.spgBlocked='1';e.disabled=true;e.setAttribute('aria-disabled','true')}})}
  root.addEventListener('click',e=>{const a=e.target.closest('[data-a]')?.dataset.a;if(!a)return;if(a==='min'){root.classList.add('min');minimized=true}if(a==='open'){root.classList.remove('min');minimized=false}if(a==='close'){root.remove();style.remove();window.__SPG_ACTIVE__=false;document.documentElement.classList.remove('spg-chat-blocked')}if(a==='improve')improve();if(a==='copy')copy();if(a==='clear'){ta.value='';status.textContent=''}if(a==='send')send();if(a==='voice')voice()});
  let rec=null;function voice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){status.textContent='Voz não disponível neste navegador';return}if(rec){rec.stop();rec=null;status.textContent='';return}rec=new SR();rec.lang='pt-BR';rec.interimResults=false;rec.onresult=e=>{ta.value+=(ta.value.trim()?' ':'')+e.results[0][0].transcript};rec.onerror=()=>status.textContent='Permita o microfone para usar voz';rec.onend=()=>{rec=null};status.textContent='● ouvindo...';try{rec.start()}catch{rec=null}}
  blockNativeChat();new MutationObserver(()=>blockNativeChat()).observe(document.body,{subtree:true,childList:true});
  chrome.runtime?.onMessage?.addListener((msg)=>{if(msg.type==='OPEN_FLOAT'){root.classList.remove('min')}if(msg.type==='SET_PROMPT'){root.classList.remove('min');ta.value=msg.text;fillNativeChat(msg.text)}});
  chrome.storage.local.get(['lastPrompt'],d=>{if(d.lastPrompt)ta.value=d.lastPrompt});
})();