(() => {
  if (window.__SPG_LOADED__) return; window.__SPG_LOADED__=true;
  const style=document.createElement('style');style.textContent=`#spg-root{position:fixed;right:18px;bottom:18px;z-index:2147483647;font-family:Inter,system-ui,sans-serif}#spg-panel{width:360px;max-width:calc(100vw - 36px);background:#101116;color:#f7f7fb;border:1px solid #343744;border-radius:18px;box-shadow:0 20px 70px #0009;overflow:hidden}#spg-head{display:flex;align-items:center;justify-content:space-between;padding:12px 14px;background:#171920;cursor:move}#spg-title{font-weight:800;font-size:13px}#spg-actions button{border:0;background:transparent;color:#aaa;font-size:17px;cursor:pointer;margin-left:6px}#spg-body{padding:12px}#spg-input{width:100%;min-height:130px;box-sizing:border-box;resize:vertical;border:1px solid #353844;background:#0b0c10;color:#fff;border-radius:12px;padding:12px;outline:none}#spg-row{display:flex;gap:8px;margin-top:9px}#spg-row button{flex:1;border:1px solid #353844;background:#1a1c24;color:#eee;border-radius:10px;padding:9px;cursor:pointer}#spg-send{width:100%;margin-top:9px;border:0;border-radius:11px;padding:11px;background:#fff;color:#111;font-weight:800;cursor:pointer}#spg-bubble{width:50px;height:50px;border-radius:50%;border:1px solid #444;background:#111;color:#fff;font-size:21px;cursor:pointer;box-shadow:0 12px 35px #0008;display:none}`;document.head.appendChild(style);
  const root=document.createElement('div');root.id='spg-root';root.innerHTML=`<div id="spg-panel"><div id="spg-head"><span id="spg-title">✦ Sessão Prêmio Gustavo</span><span id="spg-actions"><button id="spg-min" title="Minimizar">—</button><button id="spg-close" title="Sair">×</button></span></div><div id="spg-body"><textarea id="spg-input" placeholder="Digite o prompt para o Lovable..."></textarea><div id="spg-row"><button id="spg-paste">📋 Colar</button><button id="spg-copy">⧉ Copiar</button><button id="spg-voice">🎙 Voz</button></div><button id="spg-send">Enviar prompt no chat do Lovable ↗</button></div></div><button id="spg-bubble">✦</button>`;document.body.appendChild(root);
  const panel=root.querySelector('#spg-panel'),bubble=root.querySelector('#spg-bubble'),input=root.querySelector('#spg-input');
  function minimize(){panel.style.display='none';bubble.style.display='block'}function restore(){panel.style.display='block';bubble.style.display='none'}
  root.querySelector('#spg-min').onclick=minimize;root.querySelector('#spg-close').onclick=()=>root.remove();bubble.onclick=restore;
  root.querySelector('#spg-copy').onclick=()=>navigator.clipboard.writeText(input.value);
  root.querySelector('#spg-paste').onclick=async()=>{try{input.value=await navigator.clipboard.readText()}catch{}};
  root.querySelector('#spg-send').onclick=()=>sendToLovable(input.value);
  let rec;const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(SR){rec=new SR();rec.lang='pt-BR';rec.onresult=e=>input.value+=(input.value?' ':'')+e.results[0][0].transcript;root.querySelector('#spg-voice').onclick=()=>rec.start()}else root.querySelector('#spg-voice').disabled=true;
  function findBox(){return [...document.querySelectorAll('textarea,input,[contenteditable="true"]')].find(el=>{const r=el.getBoundingClientRect();const s=(el.getAttribute('placeholder')||'').toLowerCase();return r.width>150&&r.height>30&&(s.includes('message')||s.includes('prompt')||s.includes('ask')||el.isContentEditable||el.tagName==='TEXTAREA')})}
  function setValue(el,text){el.focus();if(el.isContentEditable){el.textContent=text}else{const setter=Object.getOwnPropertyDescriptor(Object.getPrototypeOf(el),'value')?.set;if(setter)setter.call(el,text);else el.value=text}el.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:text}));el.dispatchEvent(new Event('change',{bubbles:true}))}
  function sendToLovable(text){text=(text||'').trim();if(!text)return;const box=findBox();if(box){setValue(box,text);box.focus();setTimeout(()=>{const btn=[...document.querySelectorAll('button')].find(b=>/send|enviar|submit/i.test((b.innerText||b.getAttribute('aria-label')||''))&&!b.disabled);if(btn)btn.click()},250)}else navigator.clipboard.writeText(text)}
  chrome.storage.local.get(['pendingLovablePrompt','openFloating'],d=>{if(d.pendingLovablePrompt){input.value=d.pendingLovablePrompt;setTimeout(()=>sendToLovable(d.pendingLovablePrompt),1200);chrome.storage.local.remove('pendingLovablePrompt')}if(d.openFloating){restore();chrome.storage.local.remove('openFloating')}});
  chrome.runtime.onMessage.addListener(msg=>{if(msg?.type==='OPEN_FLOATING')restore();if(msg?.type==='SEND_PROMPT')sendToLovable(msg.prompt)});
})();